version: "3.8"

services:
  mongodb:
    image: "mongo"
    hostname: mongo
    container_name: mongodb-dev
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=discount_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017