version: "3.8"

services:
  discounts:
    container_name: discounts
    build:
      context: .
      args:
        BASE_IMAGE: openjdk:11-jre
        PROFILE: prod
    image: moath/discounts-service
    environment:
      - spring.data.mongodb.uri=mongodb://admin:secret@mongo:27017/discount_db?authSource=admin&authMechanism=SCRAM-SHA-1
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    hostname: mongo
    container_name: mongodb-dev
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=discount_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017